### PR TITLE
fix a bug in keep_alive2() 

### PR DESCRIPTION
**Pull request by jcyongqin**
change the "i" in keep_alive2() .because of the chr() have different result in py2 and py3

### CODE REVIEW

**Comment by mchome** [comment]
Should use `bytes([var])` instead of using `chr(var)`, anyway thanks for reporting the bug.

**Comment by ly0** [comment]
ummmm...
You mentioned that `chr()` has different behavior in py2 and py3 (in fact they have a same signature, so I don't get the point), but your commit seems that has nothing to do with `chr()`.

**Comment by jcyongqin** [comment]
can you give me a email ? I will show you the log.

**Comment by ly0** [comment]
@jcyongqin latyas@gmail.com

**Pull request merged**
